### ISSUE TITLE
default value, 0.8 too loud?

### ISSUE THREAD

**Issue by grammoboy2** [adcxyz/SafetyNet#3]
In the docs it seems to advised to add a value of Safety.setLimit(0.8);
In my experience I can set the volume still far too loud (external usb soundcard, Linux, using nvim). A value of 0.1 or even 0.05 seems to work okay here.

**Comment by adcxyz** [comment]
Hi @grammoboy2 !

The help file example just shows people how to set the limit value. 
What a good value is for a specific user and setup depends on lots of things: 
 internal computer audio levels, audio hardware used and its settings, 
mixer levels, headphones and/or loudspeakers ... 
So I think there is no generally recommendable level.
